# Generated by Django 2.1.7 on 2019-03-16 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addmed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmed',
            old_name='created_date',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='addmed',
            name='author',
        ),
        migrations.RemoveField(
            model_name='addmed',
            name='coc_date',
        ),
        migrations.RemoveField(
            model_name='addmed',
            name='text',
        ),
        migrations.RemoveField(
            model_name='addmed',
            name='title',
        ),
        migrations.AddField(
            model_name='addmed',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='addmed',
            name='exp_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='addmed',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='addmed',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addmed',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
